export const MOCK_STOCKS = [
    { symbol: 'RELIANCE', name: 'Reliance Industries', price: 2950.50, type: 'Stock' },
    { symbol: 'TCS', name: 'Tata Consultancy Services', price: 4200.75, type: 'Stock' },
    { symbol: 'HDFCBANK', name: 'HDFC Bank', price: 1650.30, type: 'Stock' },
    { symbol: 'INFY', name: 'Infosys', price: 1850.45, type: 'Stock' },
    { symbol: 'ICICIBANK', name: 'ICICI Bank', price: 1100.20, type: 'Stock' },
    { symbol: 'SBIN', name: 'State Bank of India', price: 780.50, type: 'Stock' },
    { symbol: 'BHARTIARTL', name: 'Bharti Airtel', price: 1350.60, type: 'Stock' },
    { symbol: 'ITC', name: 'ITC Ltd', price: 440.30, type: 'Stock' },
    { symbol: 'L&T', name: 'Larsen & Toubro', price: 3600.80, type: 'Stock' },
    { symbol: 'HINDUNILVR', name: 'Hindustan Unilever', price: 2400.10, type: 'Stock' },
    { symbol: 'TATAMOTORS', name: 'Tata Motors', price: 980.40, type: 'Stock' },
    { symbol: 'AXISBANK', name: 'Axis Bank', price: 1050.25, type: 'Stock' },
    { symbol: 'MARUTI', name: 'Maruti Suzuki', price: 12500.00, type: 'Stock' },
    { symbol: 'SUNPHARMA', name: 'Sun Pharma', price: 1550.70, type: 'Stock' },
    { symbol: 'TITAN', name: 'Titan Company', price: 3400.90, type: 'Stock' },
    { symbol: 'BAJFINANCE', name: 'Bajaj Finance', price: 6800.50, type: 'Stock' },
    { symbol: 'ASIANPAINT', name: 'Asian Paints', price: 2900.30, type: 'Stock' },
    { symbol: 'ULTRACEMCO', name: 'UltraTech Cement', price: 10200.00, type: 'Stock' },
    { symbol: 'WIPRO', name: 'Wipro', price: 480.60, type: 'Stock' },
    { symbol: 'HCLTECH', name: 'HCL Technologies', price: 1600.40, type: 'Stock' },
    { symbol: 'NTPC', name: 'NTPC', price: 350.20, type: 'Stock' },
    { symbol: 'ONGC', name: 'ONGC', price: 280.50, type: 'Stock' },
    { symbol: 'POWERGRID', name: 'Power Grid Corp', price: 320.10, type: 'Stock' },
    { symbol: 'COALINDIA', name: 'Coal India', price: 450.80, type: 'Stock' },
    { symbol: 'TATASTEEL', name: 'Tata Steel', price: 160.30, type: 'Stock' },
    { symbol: 'JSWSTEEL', name: 'JSW Steel', price: 920.40, type: 'Stock' },
    { symbol: 'ADANIENT', name: 'Adani Enterprises', price: 3100.50, type: 'Stock' },
    { symbol: 'ADANIPORTS', name: 'Adani Ports', price: 1400.60, type: 'Stock' },
    { symbol: 'BPCL', name: 'BPCL', price: 620.70, type: 'Stock' },
    { symbol: 'GRASIM', name: 'Grasim Industries', price: 2200.80, type: 'Stock' },
    { symbol: 'BRITANNIA', name: 'Britannia', price: 5200.90, type: 'Stock' },
    { symbol: 'TECHM', name: 'Tech Mahindra', price: 1300.10, type: 'Stock' },
    { symbol: 'INDUSINDBK', name: 'IndusInd Bank', price: 1450.30, type: 'Stock' },
    { symbol: 'DIVISLAB', name: 'Divi\'s Lab', price: 4100.50, type: 'Stock' }
];

export const MOCK_OPTIONS = [
    { symbol: 'NIFTY 25000 CE', name: 'Nifty 25000 Call', price: 120.45, type: 'Option' },
    { symbol: 'NIFTY 25000 PE', name: 'Nifty 25000 Put', price: 100.30, type: 'Option' },
    { symbol: 'BANKNIFTY 51000 CE', name: 'BankNifty 51000 Call', price: 250.60, type: 'Option' },
    { symbol: 'BANKNIFTY 51000 PE', name: 'BankNifty 51000 Put', price: 210.75, type: 'Option' },
    { symbol: 'FINNIFTY 23000 CE', name: 'FinNifty 23000 Call', price: 80.20, type: 'Option' },
    { symbol: 'FINNIFTY 23000 PE', name: 'FinNifty 23000 Put', price: 75.10, type: 'Option' },
    { symbol: 'RELIANCE 3000 CE', name: 'Reliance 3000 Call', price: 45.50, type: 'Option' },
    { symbol: 'RELIANCE 2900 PE', name: 'Reliance 2900 Put', price: 30.20, type: 'Option' },
    { symbol: 'TCS 4300 CE', name: 'TCS 4300 Call', price: 60.10, type: 'Option' },
    { symbol: 'TCS 4200 PE', name: 'TCS 4200 Put', price: 40.80, type: 'Option' },
    { symbol: 'HDFC 1700 CE', name: 'HDFC 1700 Call', price: 25.30, type: 'Option' },
    { symbol: 'HDFC 1600 PE', name: 'HDFC 1600 Put', price: 15.40, type: 'Option' },
    { symbol: 'INFY 1900 CE', name: 'Infosys 1900 Call', price: 35.60, type: 'Option' },
    { symbol: 'INFY 1800 PE', name: 'Infosys 1800 Put', price: 20.90, type: 'Option' },
    { symbol: 'SBIN 800 CE', name: 'SBI 800 Call', price: 10.50, type: 'Option' },
    { symbol: 'SBIN 750 PE', name: 'SBI 750 Put', price: 8.20, type: 'Option' },
    { symbol: 'ITC 450 CE', name: 'ITC 450 Call', price: 5.40, type: 'Option' },
    { symbol: 'ITC 430 PE', name: 'ITC 430 Put', price: 3.10, type: 'Option' },
    { symbol: 'NIFTY 25500 CE', name: 'Nifty 25500 Call', price: 40.20, type: 'Option' },
    { symbol: 'NIFTY 24500 PE', name: 'Nifty 24500 Put', price: 150.80, type: 'Option' },
    { symbol: 'BANKNIFTY 52000 CE', name: 'BankNifty 52000 Call', price: 100.50, type: 'Option' },
    { symbol: 'BANKNIFTY 50000 PE', name: 'BankNifty 50000 Put', price: 350.90, type: 'Option' },
    { symbol: 'WIPRO 500 CE', name: 'Wipro 500 Call', price: 12.30, type: 'Option' },
    { symbol: 'WIPRO 480 PE', name: 'Wipro 480 Put', price: 8.40, type: 'Option' },
    { symbol: 'TATAMOTORS 1000 CE', name: 'Tata Motors 1000 Call', price: 20.60, type: 'Option' },
    { symbol: 'TATAMOTORS 950 PE', name: 'Tata Motors 950 Put', price: 15.50, type: 'Option' },
    { symbol: 'LT 3700 CE', name: 'L&T 3700 Call', price: 55.70, type: 'Option' },
    { symbol: 'LT 3500 PE', name: 'L&T 3500 Put', price: 40.30, type: 'Option' },
    { symbol: 'MARUTI 13000 CE', name: 'Maruti 13000 Call', price: 150.20, type: 'Option' },
    { symbol: 'MARUTI 12000 PE', name: 'Maruti 12000 Put', price: 100.80, type: 'Option' }
];

export const MOCK_FUTURES = [
    { symbol: 'NIFTY FUT', name: 'Nifty Future', price: 25050.00, type: 'Future' },
    { symbol: 'BANKNIFTY FUT', name: 'BankNifty Future', price: 51100.00, type: 'Future' },
    { symbol: 'RELIANCE FUT', name: 'Reliance Future', price: 2955.00, type: 'Future' },
    { symbol: 'TCS FUT', name: 'TCS Future', price: 4210.00, type: 'Future' },
    { symbol: 'HDFCBANK FUT', name: 'HDFC Bank Future', price: 1655.00, type: 'Future' },
    { symbol: 'INFY FUT', name: 'Infosys Future', price: 1855.00, type: 'Future' },
    { symbol: 'ICICIBANK FUT', name: 'ICICI Bank Future', price: 1105.00, type: 'Future' },
    { symbol: 'SBIN FUT', name: 'SBI Future', price: 785.00, type: 'Future' },
    { symbol: 'BHARTIARTL FUT', name: 'Bharti Airtel Future', price: 1355.00, type: 'Future' },
    { symbol: 'ITC FUT', name: 'ITC Future', price: 442.00, type: 'Future' },
    { symbol: 'L&T FUT', name: 'L&T Future', price: 3610.00, type: 'Future' },
    { symbol: 'HINDUNILVR FUT', name: 'HUL Future', price: 2405.00, type: 'Future' },
    { symbol: 'TATAMOTORS FUT', name: 'Tata Motors Future', price: 985.00, type: 'Future' },
    { symbol: 'AXISBANK FUT', name: 'Axis Bank Future', price: 1055.00, type: 'Future' },
    { symbol: 'MARUTI FUT', name: 'Maruti Future', price: 12550.00, type: 'Future' },
    { symbol: 'SUNPHARMA FUT', name: 'Sun Pharma Future', price: 1555.00, type: 'Future' },
    { symbol: 'TITAN FUT', name: 'Titan Future', price: 3410.00, type: 'Future' },
    { symbol: 'BAJFINANCE FUT', name: 'Bajaj Finance Future', price: 6810.00, type: 'Future' },
    { symbol: 'ASIANPAINT FUT', name: 'Asian Paints Future', price: 2910.00, type: 'Future' },
    { symbol: 'ULTRACEMCO FUT', name: 'UltraTech Future', price: 10250.00, type: 'Future' },
    { symbol: 'WIPRO FUT', name: 'Wipro Future', price: 482.00, type: 'Future' },
    { symbol: 'HCLTECH FUT', name: 'HCL Tech Future', price: 1605.00, type: 'Future' },
    { symbol: 'NTPC FUT', name: 'NTPC Future', price: 352.00, type: 'Future' },
    { symbol: 'ONGC FUT', name: 'ONGC Future', price: 282.00, type: 'Future' },
    { symbol: 'POWERGRID FUT', name: 'Power Grid Future', price: 322.00, type: 'Future' },
    { symbol: 'COALINDIA FUT', name: 'Coal India Future', price: 452.00, type: 'Future' },
    { symbol: 'TATASTEEL FUT', name: 'Tata Steel Future', price: 162.00, type: 'Future' },
    { symbol: 'JSWSTEEL FUT', name: 'JSW Steel Future', price: 922.00, type: 'Future' },
    { symbol: 'ADANIENT FUT', name: 'Adani Ent Future', price: 3110.00, type: 'Future' },
    { symbol: 'ADANIPORTS FUT', name: 'Adani Ports Future', price: 1405.00, type: 'Future' }
];

export const MOCK_MF = [
    { symbol: 'HDFC SMALL CAP', name: 'HDFC Small Cap Fund', price: 120.50, type: 'Mutual Fund' },
    { symbol: 'SBI BLUECHIP', name: 'SBI Bluechip Fund', price: 85.30, type: 'Mutual Fund' },
    { symbol: 'ICICI PRU TECH', name: 'ICICI Pru Tech Fund', price: 210.40, type: 'Mutual Fund' },
    { symbol: 'AXIS GROWTH', name: 'Axis Growth Opp Fund', price: 45.20, type: 'Mutual Fund' },
    { symbol: 'NIPPON INDIA', name: 'Nippon India Small Cap', price: 150.60, type: 'Mutual Fund' },
    { symbol: 'KOTAK EMERGING', name: 'Kotak Emerging Equity', price: 95.80, type: 'Mutual Fund' },
    { symbol: 'MIRAE ASSET', name: 'Mirae Asset Large Cap', price: 110.20, type: 'Mutual Fund' },
    { symbol: 'DSP MIDCAP', name: 'DSP Midcap Fund', price: 130.40, type: 'Mutual Fund' },
    { symbol: 'FRANKLIN TAX', name: 'Franklin India Taxshield', price: 880.50, type: 'Mutual Fund' },
    { symbol: 'UTI NIFTY 50', name: 'UTI Nifty 50 Index Fund', price: 180.30, type: 'Mutual Fund' },
    { symbol: 'ADITYA BIRLA SL', name: 'Aditya Birla SL Frontline', price: 340.10, type: 'Mutual Fund' },
    { symbol: 'TATA DIGITAL', name: 'Tata Digital India Fund', price: 42.50, type: 'Mutual Fund' },
    { symbol: 'L&T INFRA', name: 'L&T Infrastructure Fund', price: 28.90, type: 'Mutual Fund' },
    { symbol: 'PARA PARIKH', name: 'Parag Parikh Flexi Cap', price: 75.60, type: 'Mutual Fund' },
    { symbol: 'QUANT SMALL', name: 'Quant Small Cap Fund', price: 220.80, type: 'Mutual Fund' },
    { symbol: 'MOTILAL OSWAL', name: 'Motilal Oswal Midcap', price: 65.40, type: 'Mutual Fund' },
    { symbol: 'CANARA ROBECO', name: 'Canara Robeco Bluechip', price: 55.30, type: 'Mutual Fund' },
    { symbol: 'IDFC STERLING', name: 'Bandhan Sterling Value', price: 115.70, type: 'Mutual Fund' },
    { symbol: 'SUNDARAM MID', name: 'Sundaram Mid Cap Fund', price: 190.20, type: 'Mutual Fund' },
    { symbol: 'UNION SMALL', name: 'Union Small Cap Fund', price: 38.40, type: 'Mutual Fund' },
    { symbol: 'HSBC VALUE', name: 'HSBC Value Fund', price: 92.10, type: 'Mutual Fund' },
    { symbol: 'JM FINANCIAL', name: 'JM Financial Flexicap', price: 82.60, type: 'Mutual Fund' },
    { symbol: 'PGIM INDIA', name: 'PGIM India Midcap', price: 58.70, type: 'Mutual Fund' },
    { symbol: 'BARODA BNP', name: 'Baroda BNP Paribas', price: 48.90, type: 'Mutual Fund' },
    { symbol: 'MAHINDRA MANU', name: 'Mahindra Manulife', price: 25.30, type: 'Mutual Fund' },
    { symbol: 'ZERODHA NIFTY', name: 'Zerodha Nifty LargeMid', price: 12.50, type: 'Mutual Fund' },
    { symbol: 'NAVI NIFTY', name: 'Navi Nifty 50 Index', price: 15.60, type: 'Mutual Fund' },
    { symbol: 'GROWW NIFTY', name: 'Groww Nifty Total Mkt', price: 18.90, type: 'Mutual Fund' },
    { symbol: 'NJ ELSS', name: 'NJ ELSS Tax Saver', price: 11.20, type: 'Mutual Fund' },
    { symbol: 'SAMCO FLEXI', name: 'Samco Flexi Cap Fund', price: 14.80, type: 'Mutual Fund' },
    { symbol: 'TRUST MF', name: 'Trust MF Banking', price: 21.50, type: 'Mutual Fund' }
];

export const getAllMarketItems = () => {
    return [...MOCK_STOCKS, ...MOCK_OPTIONS, ...MOCK_FUTURES, ...MOCK_MF];
};
